default_state = "PowerOn"
aoseunthaoeusnth

[[states]]
name = "PowerOn"

[[states]]
name = "Manual"

[[states]]
name = "Safe"

[[states]]
name = "Armed"

[[states.checks]]
name = "AltitudeCheck"
check = "altitude"
greater_than = 200.0
transition = "Flight"

[[states.checks]]
name = "Pyro1Check"
check = "pyro1_continuity"
flag = "unset"
abort = "Safe"

[[states.checks]]
name = "Pyro2Check"
check = "pyro2_continuity"
flag = "unset"
abort = "Safe"

[[states.commands]]
object = "dataRate"
value = 1000
time = 0.0

[[states]]
name = "Flight"

[[states.checks]]
name = "ApogeeCheck"
check = "apogee"
flag = "set"
transition = "Apogee"

[[states]]
name = "Apogee"
timeout = { seconds = 0.0, transition = "Decent" }

[[states]]
name = "Descent"
delay = 4.0
timeout = { seconds = 15.0, transition = "End" }

[[states.commands]]
object = "dataRate"
value = 500
time = 0.0

[[states]]
name = "Parachute"

[[states.commands]]
object = "pyro1"
value = 1.0

[[states.commands]]
pyro2 = "enable"
delay = 10.0

[[states]]
name = "Recovery"

[[states.commands]]
beacon = "enable"
time = 0.0
