default_state = "PowerOn"

[[states]]
name = "PowerOn"

[[states]]
name = "Manual"

[[states]]
name = "Safe"

[[states]]
name = "Armed"

[[states.checks]]
name = "AltitudeCheck"
check = "altitude"
greater_than = 200.0
transition = "Flight"

[[states.checks]]
name = "Pyro1Check"
check = "pyro1_continuity"
flag = "unset"
abort = "Safe"

[[states.checks]]
name = "Pyro2Check"
check = "pyro2_continuity"
flag = "unset"
abort = "Safe"

[[states.commands]]
data_rate = 1000
delay = 0.0

[[states]]
name = "Flight"

[[states.checks]]
name = "ApogeeCheck"
check = "apogee"
flag = "set"
transition = "Apogee"

[[states]]
name = "Apogee"
[states.timeout]
seconds = 15.0
transition = "End"


[[states]]
name = "Descent"
delay = 4.0

[states.timeout]
seconds = 15.0
transition = "End"

[[states.commands]]
data_rate = 500
delay = 0.0

[[states]]
name = "Parachute"

[[states.commands]]
pyro1 = "enable"
delay = 5

[[states.commands]]
pyro2 = "enable"
delay = 10.0

[[states]]
name = "Recovery"

[[states.commands]]
beacon = "enable"
delay = 0.0
